### PR TITLE
fix #21, convert IFDRational to float

### LINKED ISSUE #21: Some EXIF tags cause elasticsearch mapper errors
**Describe the bug**
With some image EXIF data tags the application crashes because elasticsearch is not able to store the data it is given.

**Expected behavior**
It would probably be better to handle only specific EXIF data entries that can be included in the sorting algorithm, instead of blindly trying to write all available entries into the elasticsearch database.

**Desktop (please complete the following information):**
 - OS: Linux

### PR DESCRIPTION
**Pull request by fredrike**
Attempt to fix IFDRational issues (#21) using the approach suggested at: https://stackoverflow.com/a/68166706/803002

### CODE REVIEW

**Comment by fredrike** [comment]
I changed the `result[tag_name] = v` to `result[tag_name] = {"raw": v, "type": type(v)}` during testing..

Before fix:

```
(venv) fer@SynHome:~/py-image-dedup/py_image_dedup/util$ python                     
Python 3.8.12 (default, Nov 15 2021, 06:04:41)                                      
[GCC 8.5.0] on linux                                                                
Type "help", "copyright", "credits" or "license" for more information.              
>>> import image                                                                    
>>> image.get_exif_data("dsc01065.jpg")                                             
{'ResolutionUnit': {'raw': 2, 'type': <class 'int'>}, 'ExifOffset': {'raw': 218, 'type': <class 'int'>}, 'ImageDescription': {'raw': '                               ', '
type': <class 'str'>}, 'Make': {'raw': 'SONY', 'type': <class 'str'>}, 'Model': {'raw': 'CYBERSHOT', 'type': <class 'str'>}, 'Orientation': {'raw': 1, 'type': <class 'in
t'>}, 'DateTime': {'raw': '2003:08:08 12:20:02', 'type': <class 'str'>}, 'YCbCrPositioning': {'raw': 2, 'type': <class 'int'>}, 'XResolution': {'raw': 72.0, 'type': <cla
ss 'PIL.TiffImagePlugin.IFDRational'>}, 'YResolution': {'raw': 72.0, 'type': <class 'PIL.TiffImagePlugin.IFDRational'>}, 'ExifVersion': {'raw': b'0220', 'type': <class '
bytes'>}, 'ComponentsConfiguration': {'raw': b'\x01\x02\x03\x00', 'type': <class 'bytes'>}, 'CompressedBitsPerPixel': {'raw': 2.0, 'type': <class 'PIL.TiffImagePlugin.IF
DRational'>}, 'DateTimeOriginal': {'raw': '2003:08:08 12:20:02', 'type': <class 'str'>}, 'DateTimeDigitized': {'raw': '2003:08:08 12:20:02', 'type': <class 'str'>}, 'Exp
osureBiasValue': {'raw': 0.0, 'type': <class 'PIL.TiffImagePlugin.IFDRational'>}, 'MaxApertureValue': {'raw': 3.875, 'type': <class 'PIL.TiffImagePlugin.IFDRational'>}, 
'MeteringMode': {'raw': 5, 'type': <class 'int'>}, 'LightSource': {'raw': 1, 'type': <class 'int'>}, 'Flash': {'raw': 0, 'type': <class 'int'>}, 'FocalLength': {'raw': 1
2.6, 'type': <class 'PIL.TiffImagePlugin.IFDRational'>}, 'ColorSpace': {'raw': 1, 'type': <class 'int'>}, 'ExifImageWidth': {'raw': 1280, 'type': <class 'int'>}, 'ExifIn
teroperabilityOffset': {'raw': 636, 'type': <class 'int'>}, 'SceneCaptureType': {'raw': 0, 'type': <class 'int'>}, 'ExifImageHeight': {'raw': 960, 'type': <class 'int'>}
, 'FileSource': {'raw': b'\x03', 'type': <class 'bytes'>}, 'ExposureTime': {'raw': 0.002, 'type': <class 'PIL.TiffImagePlugin.IFDRational'>}, 'FNumber': {'raw': 6.3, 'ty
pe': <class 'PIL.TiffImagePlugin.IFDRational'>}, 'SceneType': {'raw': b'\x01', 'type': <class 'bytes'>}, 'ExposureProgram': {'raw': 2, 'type': <class 'int'>}, 'CustomRen
dered': {'raw': 0, 'type': <class 'int'>}, 'ISOSpeedRatings': {'raw': 100, 'type': <class 'int'>}, 'ExposureMode': {'raw': 0, 'type': <class 'int'>}, 'FlashPixVersion': 
{'raw': b'0100', 'type': <class 'bytes'>}, 'WhiteBalance': {'raw': 1, 'type': <class 'int'>}}
```

After fix:

```
(venv) fer@SynHome:~/py-image-dedup/py_image_dedup/util$ python                                                                                                          
Python 3.8.12 (default, Nov 15 2021, 06:04:41)                                                                                                                           
[GCC 8.5.0] on linux                                                                                                                                                     
Type "help", "copyright", "credits" or "license" for more information.              
>>> import image                                                                    
>>> image.get_exif_data("dsc01065.jpg")                                                                                                                                  
{'ResolutionUnit': {'raw': 2, 'type': <class 'int'>}, 'ExifOffset': {'raw': 218, 'type': <class 'int'>}, 'ImageDescription': {'raw': '                               ', '
type': <class 'str'>}, 'Make': {'raw': 'SONY', 'type': <class 'str'>}, 'Model': {'raw': 'CYBERSHOT', 'type': <class 'str'>}, 'Orientation': {'raw': 1, 'type': <class 'in
t'>}, 'DateTime': {'raw': '2003:08:08 12:20:02', 'type': <class 'str'>}, 'YCbCrPositioning': {'raw': 2, 'type': <class 'int'>}, 'XResolution': {'raw': 72.0, 'type': <cla
ss 'float'>}, 'YResolution': {'raw': 72.0, 'type': <class 'float'>}, 'ExifVersion': {'raw': b'0220', 'type': <class 'bytes'>}, 'ComponentsConfiguration': {'raw': b'\x01\
x02\x03\x00', 'type': <class 'bytes'>}, 'CompressedBitsPerPixel': {'raw': 2.0, 'type': <class 'float'>}, 'DateTimeOriginal': {'raw': '2003:08:08 12:20:02', 'type': <clas
s 'str'>}, 'DateTimeDigitized': {'raw': '2003:08:08 12:20:02', 'type': <class 'str'>}, 'ExposureBiasValue': {'raw': 0.0, 'type': <class 'float'>}, 'MaxApertureValue': {'
raw': 3.875, 'type': <class 'float'>}, 'MeteringMode': {'raw': 5, 'type': <class 'int'>}, 'LightSource': {'raw': 1, 'type': <class 'int'>}, 'Flash': {'raw': 0, 'type': <
class 'int'>}, 'FocalLength': {'raw': 12.6, 'type': <class 'float'>}, 'ColorSpace': {'raw': 1, 'type': <class 'int'>}, 'ExifImageWidth': {'raw': 1280, 'type': <class 'in
t'>}, 'ExifInteroperabilityOffset': {'raw': 636, 'type': <class 'int'>}, 'SceneCaptureType': {'raw': 0, 'type': <class 'int'>}, 'ExifImageHeight': {'raw': 960, 'type': <
class 'int'>}, 'FileSource': {'raw': b'\x03', 'type': <class 'bytes'>}, 'ExposureTime': {'raw': 0.002, 'type': <class 'float'>}, 'FNumber': {'raw': 6.3, 'type': <class '
float'>}, 'SceneType': {'raw': b'\x01', 'type': <class 'bytes'>}, 'ExposureProgram': {'raw': 2, 'type': <class 'int'>}, 'CustomRendered': {'raw': 0, 'type': <class 'int'
>}, 'ISOSpeedRatings': {'raw': 100, 'type': <class 'int'>}, 'ExposureMode': {'raw': 0, 'type': <class 'int'>}, 'FlashPixVersion': {'raw': b'0100', 'type': <class 'bytes'
>}, 'WhiteBalance': {'raw': 1, 'type': <class 'int'>}}                                 
```

**Comment by markusressel** [comment]
Thx, if I understand it correctly, this should fix #90, right?

**Comment by fredrike** [comment]
> Thx, if I understand it correctly, this should fix #90, right?

Yes, it fixes both #90 and #21.

**Comment by fredrike** [comment]
I've not managed to run it though the generated docker image from `Docker build` fails on my system:

```
py-image-dedup_py-image-dedup_1 exited with code 1                                                                                                                       
py-image-dedup_1  | Traceback (most recent call last):                                                                                                                   
py-image-dedup_1  |   File "/usr/local/bin/py-image-dedup", line 2, in <module>                                                                                          
py-image-dedup_1  |     from py_image_dedup.cli import cli                                                                                                               
py-image-dedup_1  | ModuleNotFoundError: No module named 'py_image_dedup.cli'       
```

**Comment by markusressel** [comment]
Its working on my end :thinking: 
If you continue to have issues please open a new issue and describe in more detail :)

**Pull request merged**
